### PR TITLE
PMM-1922 Set pmm-server as instance for all component on the server

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by AlekSi** [comment]
We will lose historical data. Are we fine with this?

**Comment by delgod** [comment]
it will be not lost but has another tag, we can use both tags in dashboards - if it is needed.

**Comment by AlekSi** [comment]
> it will be not lost but has another tag
It will be a separate time series. In practice, it means this data is lost for the customer, even if it is still in the storage.

We should fix dashboard first.

**Comment by rnovikovP** [comment]
@AlekSi  thanks for the reminder. 
I've rechecked dashboards (the new one )  and looks like we not using `instance="prometheus" `
Should we check something else?

**Comment by AlekSi** [comment]
We do. It is `instance=\"prometheus\"` in JSON. For example: https://github.com/percona/grafana-dashboards/blob/57c7e952a86aa4dc54a16c98c606b8b381f9a11d/pmm-app/src/dashboards/Prometheus.json#L833

**Comment by rnovikovP** [comment]
Thanks!  will write task to change this  to use "or"

**Comment by rnovikovP** [comment]
https://github.com/percona/grafana-dashboards/pull/117 merged, so we can merge this one too

**Pull request merged**
