### PR TITLE
PMM-9060 remove grafana section of static supervisord.conf

### PR DESCRIPTION
**Pull request by jprukner**
It's been moved over to pmm-managed and is now generated on demand.

### CODE REVIEW

**Comment by atymchuk** [comment]
> It's been moved over to pmm-managed and is now generated on demand.

Let's remember to generate it before grafana starts for the first time.

**Comment by jprukner** [comment]
> > It's been moved over to pmm-managed and is now generated on demand.
> 
> Let's remember to generate it before grafana starts for the first time.

what do you mean? Grafana starts thanks to supervisord for the first time, does not it?

**Comment by atymchuk** [comment]
> > > It's been moved over to pmm-managed and is now generated on demand.
> > 
> > 
> > Let's remember to generate it before grafana starts for the first time.
> 
> what do you mean? Grafana starts thanks to supervisord for the first time, does not it?

That's exactly what I mean. It won't start if supervisord doesn't find the config in `/etc/supervisord.d/grafana.ini`.

**Comment by nikita-b** [comment]
It should be fine if you create config with pmm-managed. We restart pmm-managed and after this, we apply a new supervisor config:
https://github.com/percona/pmm-update/blob/main/ansible/playbook/tasks/update.yml#L99

**Review by atymchuk — APPROVED** [review]

**Review by nikita-b — APPROVED** [review]

**Pull request merged**
