### PR TITLE
PMM-4970 Clickhouse Plugin is not working

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by AlekSi** [comment]
Feature build is a must.

**Comment by rnovikovP** [comment]
Let's run tests  Agains FB as well.

Also will be good  to have some explain where and what fixed

**Comment by adivinho** [comment]
> Feature build is a must.

server docker - perconalab/pmm-server-fb:PR-527-2077f67

**Comment by AlekSi** [comment]
@rnovikovP Please merge once you check https://github.com/Percona-Lab/pmm-submodules/pull/527

**Pull request merged**
