### PR TITLE
wait some time for the other transaction to finish

### LINKED ISSUE #13: Failed to build via docker compose
Hi,

I would like to build pmm-server via docker compose but it failed.
I got the following error:

> Step 8/21 : RUN curl -s -LO https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.2-1481203731_amd64.deb && 	dpkg -i grafana_4.0.2-1481203731_amd64.deb && 	git clone https://github.com/percona/grafana-dashboards.git && 	/opt/grafana-postinstall.sh && 	cp /opt/VERSION /var/lib/grafana/ && 	rm -rf grafana_4.0.2-1481203731_amd64.deb grafana-dashboards/.git
>  ---> Running in ada5a606b63d
> Selecting previously unselected package grafana.
> (Reading database ... 15280 files and directories currently installed.)
> Preparing to unpack grafana_4.0.2-1481203731_amd64.deb ...
> Unpacking grafana (4.0.2-1481203731) ...
> Setting up grafana (4.0.2-1481203731) ...
> Adding system user `grafana' (UID 103) ...
> Adding new user `grafana' (UID 103) with group `grafana' ...
> Not creating home directory `/usr/share/grafana'.
> ### NOT starting grafana-server by default on bootup, please execute
>  sudo update-rc.d grafana-server defaults 95 10
> ### In order to start grafana-server, execute
>  sudo service grafana-server start
> Processing triggers for ureadahead (0.100.0-16) ...
> Cloning into 'grafana-dashboards'...
>  * Starting Grafana Server
>    ...done.
> Traceback (most recent call last):
>   File "/opt/import-dashboards.py", line 118, in <module>
>     main()
>   File "/opt/import-dashboards.py", line 44, in main
>     "VALUES (1, 'PMM Dashboard Import', '%s', 'Admin', datetime('now'), datetime('now'))" % (db_key,))
> sqlite3.OperationalError: database is locked
> ERROR: Service 'pmm-data' failed to build: The command '/bin/sh -c curl -s -LO https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.2-1481203731_amd64.deb && 	dpkg -i grafana_4.0.2-1481203731_amd64.deb && 	git clone https://github.com/percona/grafana-dashboards.git && 	/opt/grafana-postinstall.sh && 	cp /opt/VERSION /var/lib/grafana/ && 	rm -rf grafana_4.0.2-1481203731_amd64.deb grafana-dashboards/.git' returned a non-zero code: 1

### PR DESCRIPTION
**Pull request by delgod**
ticket https://jira.percona.com/browse/PMM-536

root of the issue - it is needed to wait some time for the other transaction to finish.
So I added [PRAGMA busy_timeout](https://www.sqlite.org/pragma.html#pragma_busy_timeout) before "REPLACE INTO" call.

### CODE REVIEW

**Comment by asrob** [comment]
Hi @delgod,

I applied your patch but I got another error. I would like to create an issue in your JIRA instance (https://jira.percona.com/secure/RapidBoard.jspa?rapidView=68&projectKey=PMM&view=planning) but I could not create it.
So I would like to copy here that output I got:

> Adding system user `grafana' (UID 103) ...
> Adding new user `grafana' (UID 103) with group `grafana' ...
> Not creating home directory `/usr/share/grafana'.
> ### NOT starting grafana-server by default on bootup, please execute
>  sudo update-rc.d grafana-server defaults 95 10
> ### In order to start grafana-server, execute
>  sudo service grafana-server start
> Processing triggers for ureadahead (0.100.0-16) ...
> Cloning into 'grafana-dashboards'...
>  * Starting Grafana Server
>    ...done.
> Traceback (most recent call last):
>   File "/opt/import-dashboards.py", line 119, in <module>
>     main()
>   File "/opt/import-dashboards.py", line 45, in main
>     "VALUES (1, 'PMM Dashboard Import', '%s', 'Admin', datetime('now'), datetime('now'))" % (db_key,))
> sqlite3.OperationalError: no such table: api_key
> ERROR: Service 'pmm-data' failed to build: The command '/bin/sh -c curl -s -LO https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.2-1481203731_amd64.deb && 	dpkg -i grafana_4.0.2-1481203731_amd64.deb && 	git clone https://github.com/percona/grafana-dashboards.git && 	/opt/grafana-postinstall.sh && 	cp /opt/VERSION /var/lib/grafana/ && 	rm -rf grafana_4.0.2-1481203731_amd64.deb grafana-dashboards/.git' returned a non-zero code: 1



AFAIK table `api_key` is missing.

**Comment by delgod** [comment]
Hi @asrob,

hmm, can you run one more time the following commands?
```
git clone https://github.com/delgod/pmm-server.git
cd pmm-server
git checkout issue-13
docker stop pmm-server pmm-data
docker rm pmm-server pmm-data
docker-compose up
```
NB: `git checkout issue-13` command is very important

**Comment by asrob** [comment]
Hi @delgod,

Well, it works with this repository but I increased timeout to "60000".

Thank you!

**Comment by askomorokhov** [comment]
Looks good to me. 👍

**Pull request merged**
