### PR TITLE
PMM-5375 import-dashboards.py endlessly restarts Grafana

### PR DESCRIPTION
**Pull request by adivinho**
It's required to extend additional logs on copytree commands too.
Also I have noticed an extra unnecessary command that can be removed from the script.

### CODE REVIEW

**Comment by adivinho** [comment]
The situation with remain folders can be fixed by using copy function instead of copytree.
It is possible a situation when two versions of the same plugin would be present.
Screenshot_20200325_130313
But Grafana takes only the latest version of a plugin.
Screenshot_20200325_130102
Screenshot_20200325_130122

**Comment by AlekSi** [comment]
> The situation with remain folders can be fixed 

How can we test it? Are we able to reproduce that problem?

**Comment by adivinho** [comment]
> How can we test it? Are we able to reproduce that problem?

I have tested it by commenting used folders removing function (rmtree) in the script.
So it leads to a similar situation with remain folders as in the ticket.

**Comment by atymchuk** [comment]
Closing this as stale. Please re-open if needed.

**Pull request closed without merging**
